### ISSUE TITLE
license for CFP_Ultra

### ISSUE THREAD

**Issue by seandiggity** [kaputnikGo/CFP_Ultra#1]
What is the license status of this project? We're working on some ultrasonic tracking for Yale Privacy Lab and would love to start hacking on this code (potentially for an Android app that we would package for F-Droid), but we want to make sure it's available under a Free and Open-Source License.

**Comment by kaputnikGo** [comment]
Hi, i always make stuff here available under https://creativecommons.org/licenses/by-nc-sa/4.0/ and its equivalents. However the file Goertzel.java uses an implementation of the algorithm found here:
Banks, Kevin. “The Goertzel Algorithm.” Embedded Systems Programming15, 9 (2002): 34–42

Also in use is a function in ProcessAudioValue.java :: private String getCorrespondingChar(int freq) that is derived from a decompiled SilverPush app that associates specific near ultra high frequencies to specific alphabet characters.

I am interested in this area in general so feel free to keep me informed, especially if you produce an Fdroid app, or if I can help in any way.

**Comment by seandiggity** [comment]
Discussing on the duplicate Issue #1 for PilferShush, so closing this.  Thanks for the prompt replies.

https://github.com/kaputnikGo/PilferShush/issues/1
